name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '💣 Breaking Change'
    labels:
      - 'Breaking Change 💣'
  - title: '🚀 Features'
    labels:
      - 'Feature 🎁'
      - 'Enhancement ✨'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Bug 🐛'
  - title: '🔨 Maintenance '
    label: 'Maintenance 🔨'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
