---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev

version: 2
jobs:
  build-maas-ui:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd ui && yarn run build
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ui/node_modules

  lint-maas-ui:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd ui && yarn run lint
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ui/node_modules

  test-maas-ui:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd ui && yarn run test --max-workers=2
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ui/node_modules

  build-legacy-ui:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd legacy && yarn run build
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - legacy/node_modules

  lint-legacy-ui:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd legacy && yarn run lint
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - legacy/node_modules

  test-legacy-ui:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd legacy && yarn run test --max-workers=2
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - legacy/node_modules

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - build-maas-ui
      - lint-maas-ui
      - test-maas-ui
      - build-legacy-ui
      - lint-legacy-ui
      - test-maas-ui

