---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev:v1.6.7

version: 2
jobs:
  test-cypress:
    docker:
      - image: cypress/base:12.16.1
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      - run: yarn test-cypress

workflows:
  version: 2
  test_cypress:
    jobs:
      - test-cypress
