---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev:v1.6.7

version: 2
jobs:
  test-cypress:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Set environment variables
          command: |
            echo 'export IP_ADDRESS=$(hostname -I | cut -d" " -f1)' >> $BASH_ENV
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'export POSTGRES_VERSION="10"' >> $BASH_ENV
            echo 'export MAAS_DBNAME="maasdb"' >> $BASH_ENV
            echo 'export MAAS_DBUSER="maas"' >> $BASH_ENV
            echo 'export MAAS_DBPASS="maasdbpass"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install system dependencies
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5DC22404A6F9F1CA 78BD65473CB3BD13
            sudo apt-get update && sudo apt-get install -y curl ca-certificates gnupg
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
            sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
            sudo apt-get update && sudo apt-get install --yes \
            build-essential libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 \
            libnss3 libxss1 libasound2 libxtst6 nodejs postgresql-$POSTGRES_VERSION snapd \
            software-properties-common xauth xvfb yarn
      - run:
          name: Install Node v12.14.1 LTS, node modules and verify cypress
          command: |
            nvm install v12.14.1
            node -v
            nvm alias default v12.14.1
            yarn install
            ./node_modules/.bin/cypress verify
      - run:
          name: Install MAAS snap and set up postgres database
          command: |
            sudo systemctl enable snapd
            sudo snap install maas --channel=latest/edge
            sudo -iu postgres psql -c "CREATE USER \"$MAAS_DBUSER\" WITH ENCRYPTED PASSWORD '$MAAS_DBPASS'" >/dev/null
            sudo -iu postgres createdb -O "$MAAS_DBUSER" "$MAAS_DBNAME" >/dev/null
            pg_hba="/etc/postgresql/$POSTGRES_VERSION/main/pg_hba.conf"
            sudo sh -c "echo grep -q '^host[[:space:]]\\+${MAAS_DBNAME}\\b' '$pg_hba' || printf 'host\t%s\t%s\t0/0\tmd5\n' '$MAAS_DBNAME' '$MAAS_DBUSER' >> '$pg_hba'"
      - run:
          name: Initialise MAAS
          command: |
            sudo maas init region+rack \
              --maas-url=http://$IP_ADDRESS:5240/MAAS \
              --database-uri=postgres://$MAAS_DBUSER:$MAAS_DBPASS@localhost/$MAAS_DBNAME
            sudo maas createadmin \
              --username=admin \
              --password=test \
              --email=fake@email.com
            # Uncomment when maas config bug is fixed on the backend
            # https://bugs.launchpad.net/maas/+bug/1879205
            # sudo maas config
      - run:
          name: Set proxy url and start cypress tests
          command: |
            sed "1s/.*/MAAS_URL=\"http:\/\/$IP_ADDRESS:5240\/\"/" proxy/.env > proxy/.env.local
            yarn test-cypress

workflows:
  version: 2
  test_cypress:
    jobs:
      - test-cypress
