name: Bundle Size

on:
  push:
    branches:
      - ci-bundle-size-action
  pull_request:
    branches:
      - main

jobs:
  bundle-size:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Restore node_modules
        id: yarn-cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 yarn install
      - name: Build assets
        run: yarn build
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          clean-script: "clean"
