name: MAAS Docs link checker
on:
  schedule:
    - cron: "0 14 * * 1-5" # At 14:00 every day-of-week from Monday through Friday.
  push:
    branches:
      - main
      - "3.5"
      - "MAASENG-4310-update-docs-links"

jobs:
  docs:
    name: maas.io/docs links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run docs links checks
        run: yarn test-docs-links
      - name: Create issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          WORKFLOW: ${{ github.workflow }}
        with:
          filename: .github/ISSUE_TEMPLATE/ci-failure.md
          update_existing: true
