name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Test, build and lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: CYPRESS_INSTALL_BINARY=0 yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build-all
        env:
          CI: true
  betterer:
    name: Betterer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: CYPRESS_INSTALL_BINARY=0 yarn install
      - run: yarn betterer > results.txt
        env:
          CI: true
      - name: Upload betterer results
        uses: actions/upload-artifact@v1
        with:
          name: betterer-report
          path: results.txt
